# Generated by Django 2.2.6 on 2019-10-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture_url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
